plugins: cmd: show real time command progress on shell
facebookincubator/contest pull request #137
Opened 2020-08-20 17:09 UTC by v-thakkar

Currently, cmd plugin shows the output after a command finishes the job. This patch aims to show the real-time command progress on the shell. This can be useful while monitoring the progress of jobs.

Signed-off-by: Vaishali Thakkar <vaishali.thakkar@9elements.com>

2020-11-04 16:25 UTC, xaionaro requested changes

2020-11-04 16:25 UTC, xaionaro commented on plugins/teststeps/cmd/cmd.go
> +		cmd.Stderr = io.MultiWriter(os.Stderr, &stderrBuf)
Same comment as here: https://github.com/facebookincubator/contest/pull/156#discussion_r517464920

2020-11-05 11:07 UTC, tfg13 commented
Can we continue the conversation on the other PR? - or this one, but only one please :)

2020-11-16 10:40 UTC, walterchris commented
This can be closed due to #156.

2020-11-16 11:31 UTC, closed without merging