plugins/teststeps/sshcmd: Print output to buffer and stdout
facebookincubator/contest pull request #156
Opened 2020-10-27 13:40 UTC by walterchris

2020-10-29 16:43 UTC, tfg13 commented
Does this mean the output gets effectively logged twice, once by piping it to stdout and then again when the command finishes and the "info stdout was: ..." logging prints it again?

2020-10-29 17:01 UTC, walterchris commented
> Does this mean the output gets effectively logged twice, once by piping it to stdout and then again when the command finishes and the "info stdout was: ..." logging prints it again?

Yeah.. I am used to gerrit nowadays - I need to clean this up. I had everything in one branch - and tried to divide it feature-wise afterwards. Looks like I did not do a good job at all.

2020-11-04 16:19 UTC, xaionaro requested changes

2020-11-04 16:19 UTC, xaionaro commented on plugins/teststeps/sshcmd/sshcmd.go
> +		session.Stderr = io.MultiWriter(os.Stderr, &stderrBuf)
I think this is wrong to non-optionally hardcode `os.Stdout`/`os.Stderr` here. Can we add an option which enables this `os.Stdout`/`os.Stderr` injection? And add a comment why such options could be needed.

2020-11-16 10:17 UTC, closed without merging