use replica storage for status calls
facebookincubator/contest pull request #227
Opened 2021-02-11 11:50 UTC by mkelly121

Added a read-only storage engine to be used in job status calls.

New methods `FetchAsync`, `GetJobReportAsync` and `GetJobRequestAsync` will use this read-only storage

2021-02-11 14:22 UTC, tfg13 requested changes
This looks good! Just some minor changes left

2021-02-11 14:22 UTC, tfg13 commented on cmds/contest/main.go
> +	replicaDBURI := *flagDBURI
Drop a comment here that this is just pointing to the main database for now, but could be used to connect to a replica

2021-02-11 14:22 UTC, tfg13 commented on cmds/contest/main.go
> +	}
lets fetch the version and compare it to the main one. This is by no means a check that we actually talk to the same DB, but if the version numbers are different something is very wrong and we should exit immediately

2021-02-11 14:22 UTC, tfg13 commented on pkg/jobmanager/jobmanager.go
> +	jobStorageManager storage.JobStorageManager
accidental change?

2021-02-11 14:22 UTC, tfg13 commented on pkg/storage/storage.go
> +func SetStorageAsync(storageEngine Storage) error {
Maybe name this `SetAsyncStorage`, also copy-paste in first word of the doc comment :)

2021-02-12 17:59 UTC, tfg13 approved these changes
one super minor nit, only if you want to

2021-02-12 17:59 UTC, tfg13 commented on pkg/storage/job.go
> +	return report, nil
isn't this exactly the same as:
```suggestion
	return storage.GetJobReport(jobID)
```

2021-02-12 17:59 UTC, tfg13 commented on pkg/storage/job.go
> +	report, err := storageAsync.GetJobReport(jobID)
same

2021-02-15 13:14 UTC, merged

2021-02-22 17:44 UTC, rojer9-fb commented
just ran into this while rebasing - no objections in principle but the "Async" suffix for storage methods seems confusing - usually "FooAsync" means "do Foo in a non-blocking manner", not "obtain a possibly stale version of Foo".

2021-02-22 17:46 UTC, tfg13 commented
Feel free to rename it, this was the best I could come up with on short notice, not married to the name :)